name: Schema Validation CI

on:
  workflow_run: 
    workflows: [Doc Validation CI]
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses:	actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Compile validation data
        run: ./compile.sh
      - name: Validate
        run: ./validate.sh          
    